export const BUS_SEARCH_REQUEST = "BUS_SEARCH_REQUEST";
export const BUS_SEARCH_SUCCESS = "BUS_SEARCH_SUCCESS";
export const BUS_SEARCH_FAILURE = "BUS_SEARCH_FAILURE";

// SEAT LAYOUT
export const BUS_SEAT_LAYOUT_REQUEST = "BUS_SEAT_LAYOUT_REQUEST";
export const BUS_SEAT_LAYOUT_SUCCESS = "BUS_SEAT_LAYOUT_SUCCESS";

export const CLEAR_BUS_SEARCH_REDUCER = "CLEAR_BUS_SEARCH_REDUCER";
